[package]
name = "patcher"
version = "0.0.1"
description = "An app to test APIs"
authors = ["you"]
edition = "2021"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["dialog-open", "clipboard-write-text", "dialog-message", "path-all", "window-start-dragging", "window-maximize", "window-unmaximize", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-window-state = "0.1.1"
thiserror = "1.0.61"
chrono = "0.4.38"
uuid = { version = "1.9.1", features = ["fast-rng", "v4"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
